-- Real roster import, replacing the wiped placeholder demo data. Not a
-- migration (this is data, not schema) — apply once via psql after a
-- fresh `supabase db reset`. legacy_goals/legacy_assists are the group's
-- real 2025/26 season totals from before this app existed; legacy_appearances
-- stays 0 until a fuller record with appearance counts is available.
--
-- Known open item, not resolved yet (see chat): #19 and #45 are both
-- "Ohis" with no distinguishing detail.
insert into players (nickname, full_name, legacy_goals, legacy_assists, legacy_appearances, bio) values
  ('Skinny N', 'Kunle', 69, 25, 0, null),
  ('Wale', 'Wale', 32, 48, 0, null),
  ('zeazou', 'Debo', 57, 13, 0, null),
  ('Fred', 'Fred', 39, 22, 0, null),
  ('Chukkie', 'Chuka Okonkwo', 32, 29, 0, null),
  ('Tomi', 'Tomi Akigbogun', 46, 12, 0, null),
  ('Dan J', 'Dan J', 39, 15, 0, null),
  ('AK', 'AK', 36, 17, 0, null),
  ('Gbaja', 'Gbaja', 27, 26, 0, null),
  ('Ebuka', 'Ebuka', 25, 27, 0, null),
  ('Uzkhov', 'Uzo', 32, 14, 0, null),
  ('Jerrie', 'Jerrie Rotimi', 19, 26, 0, null),
  ('E', 'Emma', 24, 19, 0, null),
  ('DB', 'Dozie', 21, 22, 0, null),
  ('Bald Hermit', 'Busayo', 18, 22, 0, null),
  ('oreos', 'Tosin Oriola', 17, 21, 0, null),
  ('Triumph', 'Triumph', 12, 24, 0, null),
  ('Black and fly', 'Moses', 11, 24, 0, null),
  ('Ohis', 'Ohis', 19, 15, 0, 'Needs a distinguishing detail, currently indistinguishable from another roster player also called Ohis.'),
  ('Allison', 'Allison', 21, 9, 0, null),
  ('Yaya', 'Yaya', 10, 20, 0, null),
  ('Emmanuel', 'Emmanuel', 16, 10, 0, null),
  ('Faddy', 'Faddy Fadipe', 8, 17, 0, null),
  ('Ekitike', 'Olumide', 15, 7, 0, null),
  ('Tony Vodka', 'Tony', 12, 8, 0, null),
  ('Killz', 'Killz Oluaye', 7, 9, 0, null),
  ('Ajegs', 'Samuel', 6, 9, 0, null),
  ('Joe', 'Joe', 7, 6, 0, null),
  ('Ajibola', 'Ajibola Grey', 6, 7, 0, null),
  ('Vinny', 'Vince', 7, 3, 0, null),
  ('Iyi', 'Iyi', 6, 4, 0, null),
  ('Machado', 'Alayo', 6, 4, 0, null),
  ('Olamide', 'Olamide', 5, 5, 0, null),
  ('Oliver', 'Tosin Oliver', 4, 6, 0, null),
  ('Ikah', 'Ikah', 2, 8, 0, null),
  ('Dante', 'Dante', 3, 6, 0, null),
  ('Oreva', 'Oreva', 7, 1, 0, null),
  ('George', 'George', 1, 7, 0, null),
  ('Iyiola', 'Iyiola', 7, 0, 0, null),
  ('Famade', 'Famade', 4, 3, 0, null),
  ('Gbolahan', 'Gbolahan', 4, 3, 0, null),
  ('Ette', 'Ette', 3, 4, 0, null),
  ('Gabriel', 'Gabriel', 2, 4, 0, null),
  ('Seyi', 'Seyi', 5, 0, 0, null),
  ('Ohis', 'Ohis', 4, 1, 0, 'Needs a distinguishing detail, currently indistinguishable from another roster player also called Ohis.'),
  ('Leonard', 'Leonard', 3, 2, 0, null),
  ('Folarin', 'Folarin', 2, 3, 0, null),
  ('Bass', 'Bass', 1, 4, 0, null),
  ('Bike', 'Doyin Ajibike', 1, 3, 0, null),
  ('Ukeme', 'Ukeme', 3, 0, 0, null),
  ('Anayo', 'Anayo', 0, 3, 0, null),
  ('Dozie', 'Dozie', 2, 0, 0, null),
  ('Nteoniro', 'Nteoniro', 1, 1, 0, null),
  ('Mustee', 'Mustee', 0, 2, 0, null),
  ('Tien', 'Tien', 0, 2, 0, null),
  ('Willis', 'Willis', 0, 2, 0, null),
  ('Laru', 'Laru', 0, 2, 0, null),
  ('Dami', 'Dami', 0, 2, 0, null),
  ('Harper', 'Harper', 0, 2, 0, null),
  ('Fredrick', 'Fredrick', 1, 0, 0, null),
  ('Mase', 'Obi', 1, 0, 0, null),
  ('Tobi', 'Tobi', 1, 0, 0, null),
  ('Dønatellø', 'Raphael Uwadone', 1, 0, 0, null),
  ('Mateta', 'Mateta', 1, 0, 0, null),
  ('Chisom', 'Chisom', 0, 1, 0, null),
  ('Falo', 'Falo', 0, 0, 0, null),
  ('Julius', 'Julius', 0, 0, 0, null),
  ('Topla', 'Topla', 0, 0, 0, null),
  ('CJ', 'CJ', 0, 0, 0, null),
  ('Damola', 'Damola', 0, 0, 0, null);
